### PR TITLE
Updates pip dependencies

### PR DESCRIPTION
**Pull request by conorsch**
Specifically, addresses safety id 38834, affecting urllib3 <1.25.9. `safety check -r requirements.txt` shows  "No known security vulnerabilities found".

### CODE REVIEW

**Review by emkll — APPROVED** [review]

**Review by zenmonkeykstop — DISMISSED** [review]
`pip-tools` will probably have to be updated as well for subsequent runs of `pip-compile` to work. The version installed is 3.7.0, which is not compatible with latest pip. Pinning it to >5.0.0 would probably do the trick.

**Comment by conorsch** [comment]
Nice find, thanks both!

**Review by kushaldas — APPROVED** [review]
The change is good. `safety` check passes. :unicorn:

**Review by kushaldas — APPROVED** [review]

**Comment by kushaldas** [comment]
I can not merge this PR (no permission). So, someone else has to do this.

**Comment by conorsch** [comment]
Thanks @kushaldas, merging now, since both you and @emkll have approved. Will work on straightening out the access list separately.

**Pull request merged**
